export const WORDS = [
  {
    wordId: '5e9f5ee35eb9e72bc21af4ca',
    status: 'Learned',
    repetitionNumber: 5,
    lastRepetition: 1592376005237,
    mistakesNumber: 1,
    userOpinionAboutWord: null,
    isWasMistakeInLastGame: false,
    isRepeatedToday: false,
    group: 0,
    page: 2,
    word: 'chart',
    image: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0043.jpg',
    audio: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0043.mp3',
    audioMeaning: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0043_meaning.mp3',
    audioExample: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0043_example.mp3',
    textMeaning: 'A <i>chart</i> is a list of information.',
    textExample: 'We used a <b>chart</b> to see how we had improved.',
    transcription: '[tʃɑːrt]',
    textExampleTranslate: 'Мы использовали график, чтобы увидеть, как мы улучшили',
    textMeaningTranslate: 'Диаграмма - это список информации',
    wordTranslate: 'диаграмма',
    wordsPerExampleSentence: 10,
  },
  {
    wordId: '5e9f5ee35eb9e72bc21af4c9',
    status: 'Learned',
    repetitionNumber: 5,
    lastRepetition: 1592376005237,
    mistakesNumber: 1,
    userOpinionAboutWord: null,
    isWasMistakeInLastGame: false,
    isRepeatedToday: false,
    id: '5e9f5ee35eb9e72bc21af4c9',
    group: 0,
    page: 2,
    word: 'among',
    image: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0042.jpg',
    audio: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0042.mp3',
    audioMeaning: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0042_meaning.mp3',
    audioExample: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0042_example.mp3',
    textMeaning: 'If you are <i>among</i> certain things, they are all around you.',
    textExample: 'There was a red apple <b>among</b> the green ones.',
    transcription: '[əmʌ̀ŋ]',
    textExampleTranslate: 'Среди зеленых было красное яблоко',
    textMeaningTranslate: 'Если вы среди определенных вещей, они все вокруг вас',
    wordTranslate: 'среди',
    wordsPerExampleSentence: 9,
  },
  {
    wordId: '5e9f5ee35eb9e72bc21af4cb',
    status: 'Learned',
    repetitionNumber: 5,
    lastRepetition: 1592376005237,
    mistakesNumber: 1,
    userOpinionAboutWord: null,
    isWasMistakeInLastGame: false,
    isRepeatedToday: false,
    id: '5e9f5ee35eb9e72bc21af4cb',
    group: 0,
    page: 2,
    word: 'cloud',
    image: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0044.jpg',
    audio: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0044.mp3',
    audioMeaning: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0044_meaning.mp3',
    audioExample: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0044_example.mp3',
    textMeaning: 'A <i>cloud</i> is a group of water drops in the sky.',
    textExample: 'The sky was filled with white <b>clouds</b>.',
    transcription: '[klaud]',
    textExampleTranslate: 'Небо было наполнено белыми облаками',
    textMeaningTranslate: 'Облако - это группа капель воды в небе',
    wordTranslate: 'облако',
    wordsPerExampleSentence: 7,
  },
  {
    wordId: '5e9f5ee35eb9e72bc21af4cc',
    status: 'Learned',
    repetitionNumber: 5,
    lastRepetition: 1592376005237,
    mistakesNumber: 1,
    userOpinionAboutWord: null,
    isWasMistakeInLastGame: false,
    isRepeatedToday: false,
    id: '5e9f5ee35eb9e72bc21af4cc',
    group: 0,
    page: 2,
    word: 'describe',
    image: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0045.jpg',
    audio: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0045.mp3',
    audioMeaning: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0045_meaning.mp3',
    audioExample: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0045_example.mp3',
    textMeaning: 'To <i>describe</i> is to say or write what someone or something is like.',
    textExample: 'They <b>described</b> their tree as colorful, with gold ribbon and a star.',
    transcription: '[diskráib]',
    textExampleTranslate: 'Они описали свое дерево как красочное, с золотой лентой и звездой',
    textMeaningTranslate: 'Описать - это сказать или написать, на что похож кто-то или что-то',
    wordTranslate: 'описать',
    wordsPerExampleSentence: 12,
  },
  {
    wordId: '5e9f5ee35eb9e72bc21af4c8',
    status: 'Learned',
    repetitionNumber: 5,
    lastRepetition: 1592376005237,
    mistakesNumber: 1,
    userOpinionAboutWord: null,
    isWasMistakeInLastGame: false,
    isRepeatedToday: false,
    id: '5e9f5ee35eb9e72bc21af4c8',
    group: 0,
    page: 2,
    word: 'alien',
    image: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0041.jpg',
    audio: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0041.mp3',
    audioMeaning: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0041_meaning.mp3',
    audioExample: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/03_0041_example.mp3',
    textMeaning: 'An <i>alien</i> is a creature from a different world.',
    textExample: 'The <b>alien</b> came in peace.',
    transcription: '[éiljən]',
    textExampleTranslate: 'пришелец пришел с миром',
    textMeaningTranslate: 'Инопланетянин - это существо из другого мира',
    wordTranslate: 'инопланетянин',
    wordsPerExampleSentence: 5,
  },
  {
    wordId: '5e9f5ee35eb9e72bc21af52d',
    status: 'Learned',
    repetitionNumber: 4,
    lastRepetition: 1492376005237,
    mistakesNumber: 2,
    userOpinionAboutWord: null,
    isWasMistakeInLastGame: false,
    isRepeatedToday: false,
    id: '5e9f5ee35eb9e72bc21af52d',
    group: 0,
    page: 7,
    word: 'arrange',
    image: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0142.jpg',
    audio: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0142.mp3',
    audioMeaning: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0142_meaning.mp3',
    audioExample: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0142_example.mp3',
    textMeaning: 'To <i>arrange</i> things is to put them in the right place.',
    textExample: 'Please <b>arrange</b> the words in order from A to Z.',
    transcription: '[əréindʒ]',
    textExampleTranslate: 'Пожалуйста, расположите слова в порядке от А до Я',
    textMeaningTranslate: 'Расставить вещи - значит поставить их в нужное место',
    wordTranslate: 'организовать',
    wordsPerExampleSentence: 10,
  },
  {
    wordId: '5e9f5ee35eb9e72bc21af52e',
    status: 'Difficult',
    repetitionNumber: 4,
    lastRepetition: 1492376005237,
    mistakesNumber: 2,
    userOpinionAboutWord: null,
    isWasMistakeInLastGame: false,
    isRepeatedToday: false,
    id: '5e9f5ee35eb9e72bc21af52e',
    group: 0,
    page: 7,
    word: 'attend',
    image: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0143.jpg',
    audio: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0143.mp3',
    audioMeaning: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0143_meaning.mp3',
    audioExample: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0143_example.mp3',
    textMeaning: 'To <i>attend</i> something is to go to it.',
    textExample: 'My sister and I <b>attend</b> the same school.',
    transcription: '[əténd]',
    textExampleTranslate: 'Мы с сестрой учимся в одной школе',
    textMeaningTranslate: 'Побывать на чем-то - значит пойти на это',
    wordTranslate: 'присутствовать',
    wordsPerExampleSentence: 8,
  },
  {
    wordId: '5e9f5ee35eb9e72bc21af52f',
    status: 'Removed',
    repetitionNumber: 4,
    lastRepetition: 1492376005237,
    mistakesNumber: 2,
    userOpinionAboutWord: null,
    isWasMistakeInLastGame: false,
    isRepeatedToday: false,
    id: '5e9f5ee35eb9e72bc21af52f',
    group: 0,
    page: 7,
    word: 'chase',
    image: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0144.jpg',
    audio: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0144.mp3',
    audioMeaning: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0144_meaning.mp3',
    audioExample: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0144_example.mp3',
    textMeaning: 'You <i>chase</i> people when you run after them and try to catch them.',
    textExample: 'I was <b>chased</b> by a dog.',
    transcription: '[ʧeis]',
    textExampleTranslate: 'Меня преследовала собака',
    textMeaningTranslate: 'Вы преследуете людей, когда бежите за ними и пытаетесь поймать их',
    wordTranslate: 'гнаться',
    wordsPerExampleSentence: 6,
  },
  {
    wordId: '5e9f5ee35eb9e72bc21af530',
    status: 'Difficult',
    repetitionNumber: 7,
    lastRepetition: 1452376005237,
    mistakesNumber: 3,
    userOpinionAboutWord: null,
    isWasMistakeInLastGame: false,
    isRepeatedToday: false,
    id: '5e9f5ee35eb9e72bc21af530',
    group: 0,
    page: 7,
    word: 'contrast',
    image: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0145.jpg',
    audio: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0145.mp3',
    audioMeaning: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0145_meaning.mp3',
    audioExample: 'https://raw.githubusercontent.com/pavelSaikov/rslang-data/master/files/08_0145_example.mp3',
    textMeaning: 'A <i>contrast</i> is a sharp difference between two things.',
    textExample: 'The <b>contrast</b> between my parents is very noticeable.',
    transcription: '[kɑ́ntræst]',
    textExampleTranslate: 'Контраст между моими родителями очень заметен',
    textMeaningTranslate: 'Контраст - это резкая разница между двумя вещами',
    wordTranslate: 'контраст',
    wordsPerExampleSentence: 8,
  },
];
