export const ERROR_MESSAGE_STATISTICS_SERVICE = {
  INVALID_ACCESS_TOKEN: 'Access Token Is Missing or Invalid',
  BAD_REQUEST: 'Bad Request',
  STATISTICS_NOT_FOUND: 'Statistics Not Found',
};

export const ERROR_MESSAGES = Object.keys(ERROR_MESSAGE_STATISTICS_SERVICE).map(
  key => ERROR_MESSAGE_STATISTICS_SERVICE[key],
);

export const ERROR_MESSAGES_RESPONSE_STATUS_MAP = new Map([
  [400, ERROR_MESSAGE_STATISTICS_SERVICE.BAD_REQUEST],
  [401, ERROR_MESSAGE_STATISTICS_SERVICE.INVALID_ACCESS_TOKEN],
  [404, ERROR_MESSAGE_STATISTICS_SERVICE.STATISTICS_NOT_FOUND],
]);

export const ONE_DAY_IN_MILLISECONDS = 24 * 60 * 60 * 1000;
