export const USER_OPINION_ABOUT_WORD = {
  EASY: 'Easy',
  WELL: 'Well',
  DIFFICULT: 'Difficult',
  REPEAT: 'Repeat',
};

export const USER_OPINION_ABOUT_WORD_TRANSLATION_MAP = new Map([
  [USER_OPINION_ABOUT_WORD.EASY, 'Легко'],
  [USER_OPINION_ABOUT_WORD.WELL, 'Нормально'],
  [USER_OPINION_ABOUT_WORD.DIFFICULT, 'Сложно'],
  [USER_OPINION_ABOUT_WORD.REPEAT, 'Повторить'],
]);

export const USER_OPINIONS_ABOUT_WORD = [
  USER_OPINION_ABOUT_WORD.EASY,
  USER_OPINION_ABOUT_WORD.WELL,
  USER_OPINION_ABOUT_WORD.DIFFICULT,
  USER_OPINION_ABOUT_WORD.REPEAT,
];

export const USER_OPINION_ABOUT_WORD_DIFFICULTY_INDEX_MAP = new Map([
  [USER_OPINION_ABOUT_WORD.REPEAT, 1],
  [USER_OPINION_ABOUT_WORD.HARD, 0.75],
  [USER_OPINION_ABOUT_WORD.WELL, 0.5],
  [USER_OPINION_ABOUT_WORD.EASY, 0.1],
]);

export const DEFAULT_USER_OPINION_ABOUT_WORD = 'Default';
