export const WORDS_PER_PAGE = 20;
export const DEFAULT_WORDS_PER_PAGE = 20;
export const DEFAULT_PAGES_IN_EACH_GROUP = 30;
export const DEFAULT_GROUPS_NUMBER = 6;

export const ERROR_MESSAGE_WORDS_SERVICE = {
  INVALID_ACCESS_TOKEN: 'Access Token Is Missing or Invalid',
  BAD_REQUEST: 'Bad Request',
  USER_WORD_NOT_FOUND: 'User Word Not Found',
};

export const ERROR_MESSAGES = Object.keys(ERROR_MESSAGE_WORDS_SERVICE).map(key => ERROR_MESSAGE_WORDS_SERVICE[key]);

export const ERROR_MESSAGES_RESPONSE_STATUS_MAP = new Map([
  [400, ERROR_MESSAGE_WORDS_SERVICE.BAD_REQUEST],
  [401, ERROR_MESSAGE_WORDS_SERVICE.INVALID_ACCESS_TOKEN],
  [404, ERROR_MESSAGE_WORDS_SERVICE.USER_WORD_NOT_FOUND],
]);
