export const PROGRESS_TYPE = {
  GAME_PROGRESS: 'Game Progress',
  NEW_WORDS_PROGRESS: 'New Words Progress',
  CARDS_PROGRESS: 'Cards Progress',
};

export const PROGRESS_TYPE_PART_COLOR_MAP = new Map([
  [PROGRESS_TYPE.GAME_PROGRESS, '#c0dbdf'],
  [PROGRESS_TYPE.NEW_WORDS_PROGRESS, '#f7e6da'],
  [PROGRESS_TYPE.CARDS_PROGRESS, '#dde4e2'],
]);

export const PROGRESS_TYPE_FILLED_PART_COLOR_MAP = new Map([
  [PROGRESS_TYPE.GAME_PROGRESS, '#438c9a'],
  [PROGRESS_TYPE.NEW_WORDS_PROGRESS, '#f7974d'],
  [PROGRESS_TYPE.CARDS_PROGRESS, '#5999a5'],
]);
