export const INPUT_STATE = {
  INITIAL: 'INITIAL',
  CORRECT: 'CORRECT',
  MISTAKE: 'MISTAKE',
};

export const INPUT_STATE_COLOR_MAP = new Map([
  [INPUT_STATE.INITIAL, '#438c9a'],
  [INPUT_STATE.CORRECT, '#3cc977'],
  [INPUT_STATE.MISTAKE, '#f45c53'],
]);
