export const MAXIMUM_TOKEN_AGE = 3 * 60 * 60 * 1000;

export const ERROR_MESSAGE_AUTHORIZATION_SERVICE = {
  INCORRECT_EMAIL_OR_PASSWORD: 'Incorrect Email Or Password',
  USER_WITH_THIS_EMAIL_EXIST: 'User With This Email Exists',
  INVALID_ACCESS_TOKEN: 'Access Token Is Missing Or Invalid',
};

export const ERROR_MESSAGES = Object.keys(ERROR_MESSAGE_AUTHORIZATION_SERVICE).map(
  key => ERROR_MESSAGE_AUTHORIZATION_SERVICE[key],
);

export const ERROR_MESSAGES_RESPONSE_STATUS_MAP = new Map([
  [401, ERROR_MESSAGE_AUTHORIZATION_SERVICE.INVALID_ACCESS_TOKEN],
  [422, ERROR_MESSAGE_AUTHORIZATION_SERVICE.INCORRECT_EMAIL_OR_PASSWORD],
  [403, ERROR_MESSAGE_AUTHORIZATION_SERVICE.INCORRECT_EMAIL_OR_PASSWORD],
  [417, ERROR_MESSAGE_AUTHORIZATION_SERVICE.USER_WITH_THIS_EMAIL_EXIST],
]);
