export const MAXIMUM_TOKEN_AGE = 3 * 60 * 60 * 1000;

export const ERROR_MESSAGE = {
  INCORRECT_EMAIL_OR_PASSWORD: 'Incorrect Email Or Password',
  USER_WITH_THIS_EMAIL_EXIST: 'User With This Email Exists',
  INVALID_ACCESS_TOKEN: 'Access Token Is Missing Or Invalid',
};

export const ERROR_MESSAGES = Object.keys(ERROR_MESSAGE).map(key => ERROR_MESSAGE[key]);

export const ERROR_MESSAGES_RESPONSE_STATUS_MAP = new Map([
  [401, ERROR_MESSAGE.INVALID_ACCESS_TOKEN],
  [422, ERROR_MESSAGE.INCORRECT_EMAIL_OR_PASSWORD],
  [403, ERROR_MESSAGE.INCORRECT_EMAIL_OR_PASSWORD],
  [417, ERROR_MESSAGE.USER_WITH_THIS_EMAIL_EXIST],
]);
